import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Navigation } from '@components/navigation/navigation'
import { AppWrapper } from '@components/app-wrapper/app-wrapper'

import 'bootstrap/dist/css/bootstrap.min.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <AppWrapper>
            <body className={inter.className}>
                <Navigation />
                {children}
            </body>
        </AppWrapper>
    )
}
